// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUH3DDLHkLKV1xXc276IN65xXmE1G4bCI',
    appId: '1:209503158758:web:baf15eebaf6e7619ca1627',
    messagingSenderId: '209503158758',
    projectId: 'loginregisterapp-6c33a',
    authDomain: 'loginregisterapp-6c33a.firebaseapp.com',
    storageBucket: 'loginregisterapp-6c33a.appspot.com',
    measurementId: 'G-N4C9RWTTSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6TVNTyALNDfzsJYbT-BuwNu0ZN-nXtY',
    appId: '1:209503158758:android:93104887bb0eedcdca1627',
    messagingSenderId: '209503158758',
    projectId: 'loginregisterapp-6c33a',
    storageBucket: 'loginregisterapp-6c33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjHROLbQlCZ9hHYKkJM1LjUxBaZnA8hA',
    appId: '1:209503158758:ios:16e8793e7941deccca1627',
    messagingSenderId: '209503158758',
    projectId: 'loginregisterapp-6c33a',
    storageBucket: 'loginregisterapp-6c33a.appspot.com',
    iosClientId:
        '209503158758-6pip94vi19oa8fs5mms32ksd4aq48abk.apps.googleusercontent.com',
    iosBundleId: 'com.ahmet.loginregister',
  );
}
